
services:
  postgres-db:
    image: postgres:14-alpine 
    container_name: chat_postgres_db
    ports:
      - "5433:5432" 
    environment:
      - POSTGRES_USER=docker      
      - POSTGRES_PASSWORD=docker  
      - POSTGRES_DB=chatdb        
    volumes:
      - ./pgdata:/var/lib/postgresql/data